server:
  port: 8080
  servlet:
    context-path: /services/be/offer-service

spring:
  application:
    name: OFFER-SERVICE
    restclient:
      user:
        url: http://localhost:8280/services/be/user-service/
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


kafka:
  bootstrap-servers: localhost:9092
  notify-topic:
    name: interview-topic


doc:
  api:
    path: /doc/api
    title: Job offer API
    description: Documentation for the Job offer API
    version: 1.0.0




