name: Deploy Offer Service to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy JAR to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_ONE_HOST }}
          username: ${{ secrets.SERVER_ONE_USER }}
          password: ${{ secrets.SERVER_ONE_PASSWORD }}
          source: target/offer-service-0.0.1-SNAPSHOT.jar
          target: /opt/offerService/

      - name: Restart Offer Service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_ONE_HOST }}
          username: ${{ secrets.SERVER_ONE_USER }}
          password: ${{ secrets.SERVER_ONE_PASSWORD }}
          script: |
            echo "🛑 Killing process on port 8086..."
            fuser -k 8082/tcp || true

            echo "🧹 Removing previous .jar..."
            rm -f /opt/offerService/offer-service-0.0.1-SNAPSHOT.jar

            echo "📦 Moving new JAR..."
            mv /opt/offerService/target/offer-service-0.0.1-SNAPSHOT.jar /opt/offerService/offer-service-0.0.1-SNAPSHOT.jar

            echo "📂 Ensuring log directory exists..."
            mkdir -p /home/${USER}/logs

            echo "🚀 Starting Offer Service..."
            nohup java -jar /opt/offerService/offer-service-0.0.1-SNAPSHOT.jar > /home/${USER}/logs/offer.log 2>&1 &

            echo "📄 Showing last 50 lines of log..."
            sleep 5
            tail -n 50 /home/${USER}/logs/offer.log
